apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-blue
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-k8s-logging
      variant: blue
  template:
    metadata:
      labels:
        app: hello-k8s-logging
        variant: blue
    spec:
      terminationGracePeriodSeconds: 5
      containers:
        - name: web-server
          image: hello-k8s-logging-web:latest
          imagePullPolicy: Never
          env:
            - name: VARIANT
              value: "blue"
          ports:
            - containerPort: 80
          volumeMounts:
            - name: varlog
              mountPath: /var/log/nginx
          livenessProbe:
            httpGet:
              path: /healthz
              port: 80
            initialDelaySeconds: 3
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /healthz
              port: 80
            initialDelaySeconds: 1
            periodSeconds: 5
        - name: log-collector
          image: fluent/fluent-bit:4.0
          volumeMounts:
            - name: varlog
              mountPath: /var/log/nginx
              readOnly: true
            - name: fb-config
              mountPath: /fluent-bit/etc
      volumes:
        - name: varlog
          emptyDir: {}
        - name: fb-config
          configMap:
            name: fb-config
