apiVersion: v1
kind: ConfigMap
metadata:
  name: fb-config
data:
  fluent-bit.conf: |
    [SERVICE]
        Flush        5
        Log_Level    info

    [INPUT]
        Name         tail
        Tag          nginx.access
        Path         /var/log/nginx/access.log
        Read_From_Head On

    [OUTPUT]
        Name         stdout
        Match        *
        Format       json_lines
