apiVersion: apps/v1
kind: Deployment
metadata:
  name: green
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-k8s-logging
      variant: green
  template:
    metadata:
      labels:
        app: hello-k8s-logging
        variant: green
    spec:
      terminationGracePeriodSeconds: 5
      containers:
        - name: web-server
          image: hello-k8s-logging-web:latest
          imagePullPolicy: Never
          args: ["green"]
          ports:
            - containerPort: 80
          livenessProbe:
            httpGet:
              path: /healthz
              port: 80
            initialDelaySeconds: 3
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /healthz
              port: 80
            initialDelaySeconds: 1
            periodSeconds: 5
