apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# Namespace は最初に作成される必要がある
namespace: hello-k8s-logging
resources:
  - namespace.yaml
  - deployment-blue.yaml
  - deployment-green.yaml
  - service-blue.yaml
  - service-green.yaml
